### PR TITLE
Implement auto completion

### PR DESCRIPTION
**Pull request by Asam237**
jtf

### CODE REVIEW

**Review by Zaker237 — APPROVED** [review]

**Comment by Asam237** [comment]
I implemented auto completion for the form "Company name" and that of "Job title" 
compautocomp
jobauto

**Comment by Asam237** [comment]
I added the "Seniority" field and the auto completion 
sssnnnnnnsss

**Comment by Zaker237** [comment]
Hi Asam why is there an Auto completion on the Compagnie name??
i don't get the idea behind it
cc @elhmn

**Comment by Zaker237** [comment]
oki nice thank you i get the point

**Review by Zaker237 — APPROVED** [review]

**Pull request merged**
