### PR TITLE
FiltersListOfRatings: Implement filters on the list of ratings

### PR DESCRIPTION
**Pull request by Asam237**
https://user-images.githubusercontent.com/34966088/154838025-8e8ecf97-2304-4142-be8d-4c72972d46c9.mp4

### CODE REVIEW

**Review by Zaker237 — APPROVED** [review]

**Review by elhmn — CHANGES_REQUESTED** [review]
Ce serait bien d'avoir un champ `Any` au debut de chaque filtre qui permet de reinitialiser le filtre

**Comment by Asam237** [comment]
annnny

**Comment by elhmn** [comment]
> annnny

Thanks, but `any` is still not selectable. We should be able to select `any` in the list

**Comment by Asam237** [comment]
https://user-images.githubusercontent.com/34966088/155076644-6a7eade5-9031-4e06-833c-bac4a1c9c239.mp4

**Comment by elhmn** [comment]
I guess there is something wrong with the implementation.


https://user-images.githubusercontent.com/5704817/155244813-de1ac415-14de-444d-b93e-d8047724d004.mp4

**Comment by elhmn** [comment]
Resolve conflict and remove space in the lists

**Comment by Asam237** [comment]
https://user-images.githubusercontent.com/34966088/155406888-805dceeb-9cfb-4b4c-a31b-11f433f9f992.mp4

**Review by elhmn — APPROVED** [review]

**Pull request merged**
